{% set version = "2024.1" %}
{% set build = 0 %}
{% set build_string = "py{}h{}_{}".format(CONDA_PY, PKG_HASH, build) %}

package:
  name: chaste
  version: {{ version }}

source:
  path: /tmp/Chaste

build:
  number: {{ build }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - python
    - pip
    - distro
    - git
    - {{ cdt('libice-devel') }}
    - {{ cdt('libsm-devel') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('libxext') }}
    - {{ cdt('libxt-devel') }}

  host:
    - boost-cpp<1.84
    - hdf5<14.0=*mpich*
    - matplotlib
    - metis
    - mpi4py
    - mpich
    - numpy
    - parmetis
    - petsc<3.20
    - petsc4py
    - python
    - sundials<7.0
    - vtk<10.0
    - xerces-c
    - xsd
    - xvfbwrapper

test:
  imports:
    - chaste
    - chaste.cell_based
    - chaste.mesh
    - chaste.ode
    - chaste.pde
    - chaste.visualization

about:
  home: https://chaste.github.io
  license: BSD-3-Clause
  summary: >
    Chaste is a general purpose simulation package for computational biology.
  dev_url: https://github.com/Chaste/Chaste/
  doc_url: https://chaste.github.io/docs/
