name: PyChaste conda tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

# Limit concurrent runs to one per branch
concurrency:
  group: pychaste-conda-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pychaste-conda-tests:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:off') }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ubuntu-latest

    env:
      CHASTE_TEST_OUTPUT: ${{ github.workspace }}/testoutput

    defaults:
      run:
        shell: bash -el {0} # -l needed to activate conda

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make build and test directories
        run: |
          mkdir -p build
          mkdir -p ${CHASTE_TEST_OUTPUT}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y castxml clang cmake xvfb

      - name: Setup Miniconda Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          use-mamba: true
          miniforge-version: latest
          environment-file: pychaste/src/py/conda/environment.yml
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,pychaste

      - name: Configure PyChaste
        run: |
          cmake \
            -DChaste_ENABLE_PYCHASTE=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX="${CONDA_PREFIX}" \
            -DCMAKE_PREFIX_PATH="${CONDA_PREFIX}" \
            -DCMAKE_LIBRARY_PATH="${CONDA_PREFIX}/lib" \
            -DBUILD_SHARED_LIBS=ON \
            -DBOOST_ROOT="${CONDA_PREFIX}" \
            -DHDF5_C_COMPILER_EXECUTABLE="${CONDA_PREFIX}/bin/h5pcc" \
            -DPETSC_DIR="${CONDA_PREFIX}" \
            -DPYTHON_EXECUTABLE="$(which python)" \
            -DVTK_DIR="${CONDA_PREFIX}" \
            -DXERCESC_INCLUDE="${CONDA_PREFIX}/include" \
            -DXERCESC_LIBRARY="${CONDA_PREFIX}/lib/libxerces-c.so" \
            -DXSD_EXECUTABLE="${CONDA_PREFIX}/bin/xsd" \
            ..
        working-directory: build

      - name: Build PyChaste
        run: |
          make -j $(nproc) pychaste
        working-directory: build

      - name: Install PyChaste
        run: |
          python3 -m pip install -v pychaste/package
        working-directory: build

      - name: Run PyChaste tests
        run: |
          xvfb-run --server-args="-screen 0 1024x768x24" \
            ctest -j $(nproc) -L pychaste --output-on-failure
        working-directory: build
